### PR TITLE
Move from OpenStreetMap to Google Maps

### PR DESCRIPTION
**Pull request by dragonfist453**
Moved from OpenStreetMap to Google Maps after clarification of something in iOS code

After this, we are using local.properties for the Google maps API key, but never pushing the API key onto Github

local.properties must have:

GOOGLE_MAPS_API_KEY=THE KEY

### CODE REVIEW

**Review by FlickerSoul — APPROVED** [review]
LGTM

**Comment by dragonfist453** [comment]
@18lz You need to use the local.properties that I sent on Whatsapp. If you use that, the map should load. Otherwise, it can't connect to Google Maps

**Comment by 18lz** [comment]
I used that but it looks like the local.properties that you sent on Whatsapp is also empty(without key). Could you double check it?

**Comment by dragonfist453** [comment]
Thank you for informing, sent the key properly

**Review by 18lz — APPROVED** [review]

**Pull request merged**
