### PR TITLE
Build UI mockups on home page include search bar, navigation button, map card and basic navigate to map page

### PR DESCRIPTION
**Pull request by FriedhelmWS**
Dimensions are not 100% to the IOS design.

The search bar is thicker than it is supposed to be, and seems to use material3's encapsulated SearchBar component there is no way to modify the height of it (kinda already dug into the source code). If we think we really want to have a "thin" search bar similar to the IOS one, we can implement our own search bar.

The top right zoom out button on the map card will navigate to a new map page, this is the page for Li and Kathrik.

The PR also contains very very basic search mock-up which demostates how to use them.

The content in this PR is only a UI mock up so there are many unfinished code, marked with TODO and FIXME.

We really need to start thinking about the data model.

image

Issue: #33

### CODE REVIEW

**Review by nextedoff — APPROVED** [review]
Looks great! It's surprising how you are making these so quick 👍 If there's any chance you could try to modularise the code even further, it would be great.

**Review by FlickerSoul — APPROVED** [review]
Looks good to me!

**Comment by FriedhelmWS** [comment]
> Looks great! It's surprising how you are making these so quick 👍 If there's any chance you could try to modularise the code even further, it would be great.

**Comment by FriedhelmWS** [comment]
> Looks great! It's surprising how you are making these so quick 👍 If there's any chance you could try to modularise the code even further, it would be great.

Yea, will do it afterwards once we have more pages so that we know how to do refactoring more effectively, I also note down some inline comments to show some possible refactoring (e.g. the top app bar).

**Review by tommyx98 — APPROVED** [review]

**Comment by dragonfist453** [comment]
I would wait for Tommy's code to be merged in first from #52 ! Although, brilliant work and I don't see any major flaws that are right outside, but would be nice to look with Tommy's code in there

**Comment by 18lz** [comment]
I am also confused about the functionality that shows nearby addresses after clicking on 'Places Nearby'. Should this be handled as part of the UI design or is it a task for the map? I'm a bit unsure about where the responsibility lies for this feature.

**Comment by FriedhelmWS** [comment]
> I am also confused about the functionality that shows nearby addresses after clicking on 'Places Nearby'. Should this be handled as part of the UI design or is it a task for the map? I'm a bit unsure about where the responsibility lies for this feature.

Yeah I mean who is responsible for what would depend on the availability of the team and how the prioritised the thing. Currently, the top task for Tommy and I would be to finish the "visible" UI part so that 1) we have something to demo and 2) not block any other team members so that they can implement functionalities with the designated UI component. That button in this PR is just a mockup without functionality for now. Feel free to implement it (possibly create a new ticket and assign it as no work should be done without tracking) if u feel it is something u are free to do.

**Pull request merged**
