### PR TITLE
Get Location and Device Heading Data

### PR DESCRIPTION
**Pull request by anisahn09**
## Main features:
- Request location (fine & coarse) permission
- Request background location permission
- Get **location data** (latitude, longitude, coarse heading) and **device heading data** every 10 seconds, save to local storage, and log into Logcat

### Additional info:
- Location and heading update starts immediately when user open the app
- Location and heading updates will still run even if users switch to another app
- Location and heading updates will only stop if user force close the app OR remove location permission

## Screenshot & Screen record

https://github.com/Soundscape-Project-UCL/Soundscape/assets/60391674/8bb500d3-4708-4889-bf99-1552368f14c1

Screenshot 2024-01-29 at 13 26 34

Close issues #31 and #54

### CODE REVIEW

**Review by dragonfist453 — APPROVED** [review]
Great. No comments!

**Comment by dragonfist453** [comment]
So... On testing on my Google Pixel 6, it crashes constantly with the Get Location, and I am finding that weird

**Comment by nextedoff** [comment]
> So... On testing on my Google Pixel 6, it crashes constantly with the Get Location, and I am finding that weird

Works on mine, maybe some Gradle issues after checkout to another branch?

**Review by nextedoff — APPROVED** [review]
Code-wise looks great, the Logcat produces the results from the sensor. And also nicely written.
If you don't mind, we will move the service package elsewhere later though, for it to look nicer, but that's going to be later anyway.

**Comment by dragonfist453** [comment]
Found out that the issue was specific to Android 14 due to a new change. Pushed code to make it more stable on that front as well as fix a permission bug in the Manifest. That should be good to go now!

**Comment by dragonfist453** [comment]
"Code-wise looks great, the Logcat produces the results from the sensor. And also nicely written.
If you don't mind, we will move the service package elsewhere later though, for it to look nicer, but that's going to be later anyway."

@nextedoff I agree. I was thinking about if it should move to core or not, but I think it should be okay being where it is because it is only relevant to the app. Does it make sense to move it out as it generates notifications and sends intents? I didn't feel so

**Pull request merged**
